# This is a config for E2B sandbox template.
# You can use template ID (zyf5223sc1shsfan5jkl) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("zyf5223sc1shsfan5jkl") # Sync sandbox
# sandbox = await AsyncSandbox.create("zyf5223sc1shsfan5jkl") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('zyf5223sc1shsfan5jkl')

team_id = "460355b3-4f64-48f9-9a16-4442817f79f5"
memory_mb = 4_096
cpu_count = 4
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_id = "zyf5223sc1shsfan5jkl"
